var data = {
    "data": [
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 1920.0,
            "dung_tich": 9.0e3,
            "kinh_do": 20.808208,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Đà",
            "nam_hoat_dong": "12/1/1994",
            "nam_khoi_cong": "11/1/1979",
            "quy_mo": "Lớn",
            "san_luong": 8160.0,
            "ten_thuy_dien": "Hòa Bình",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Đà",
            "vi_do": 105.323278,
            "vi_tri_hanh_chinh": "Tp. Hòa Bình tỉnh Hòa Bình",
            "von_dau_tu": 0.0
        },
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 2.4e3,
            "dung_tich": 9260.0,
            "kinh_do": 21.496389,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Đà",
            "nam_hoat_dong": "12/1/2012",
            "nam_khoi_cong": "12/1/2005",
            "quy_mo": "Lớn",
            "san_luong": 9429.0,
            "ten_thuy_dien": "Sơn La",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Đà",
            "vi_do": 103.995,
            "vi_tri_hanh_chinh": "xã Ít Ong huyện Mường La tỉnh Sơn La",
            "von_dau_tu": 36933.0
        },
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 1.2e3,
            "dung_tich": 1215.0,
            "kinh_do": 22.137922,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Đà",
            "nam_hoat_dong": "12/1/2016",
            "nam_khoi_cong": "1/1/2011",
            "quy_mo": "Lớn",
            "san_luong": 4670.0,
            "ten_thuy_dien": "Lai Châu",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Đà",
            "vi_do": 102.98385,
            "vi_tri_hanh_chinh": "Tt. Nậm Nhùn huyện Nậm Nhùn tỉnh Lai Châu",
            "von_dau_tu": 3.57e4
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 140.0,
            "dung_tich": null,
            "kinh_do": 22.566145,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/11/1905",
            "nam_khoi_cong": "7/8/1905",
            "quy_mo": null,
            "san_luong": 530.0,
            "ten_thuy_dien": "Pắc Ma",
            "tinh_trang": null,
            "tren_song": "Sông Đà",
            "vi_do": 102.517806,
            "vi_tri_hanh_chinh": "xã Mù Cả, Mường Tè và Ka Lăng huyện Mường Tè tỉnh Lai Châu[1]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "Công ty cổ phần Thủy điện Thác Bà",
            "cong_xuat": 120.0,
            "dung_tich": 2940.0,
            "kinh_do": 21.747064,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": "Chảy ",
            "nam_hoat_dong": "5/24/1905",
            "nam_khoi_cong": "5/17/1905",
            "quy_mo": "Lớn",
            "san_luong": 400.0,
            "ten_thuy_dien": "Thác Bà",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Chảy",
            "vi_do": 105.023258,
            "vi_tri_hanh_chinh": "huyện Yên Bình tỉnh Yên Bái",
            "von_dau_tu": 0.0
        },
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 342.0,
            "dung_tich": 2245.0,
            "kinh_do": 22.360036,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Gâm",
            "nam_hoat_dong": "6/30/1905",
            "nam_khoi_cong": "6/24/1905",
            "quy_mo": "Lớn",
            "san_luong": 1295.0,
            "ten_thuy_dien": "Tuyên Quang",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Gâm",
            "vi_do": 105.398469,
            "vi_tri_hanh_chinh": "huyện Na Hang tỉnh Tuyên Quang",
            "von_dau_tu": 7.5e3
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 110.0,
            "dung_tich": null,
            "kinh_do": 23.143267,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/1/2012",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": null,
            "san_luong": 507.0,
            "ten_thuy_dien": "Nho Quế 3",
            "tinh_trang": null,
            "tren_song": "Nho Quế",
            "vi_do": 105.515419,
            "vi_tri_hanh_chinh": "xã Lũng Pù và Sơn Vĩ huyện Mèo Vạc tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "Công ty cổ phần thủy điện Nậm Chiến",
            "cong_xuat": 200.0,
            "dung_tich": 154.0,
            "kinh_do": 21.593544,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": "Chiến",
            "nam_hoat_dong": "7/5/1905",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": "Lớn",
            "san_luong": 791.0,
            "ten_thuy_dien": "Nậm Chiến 1",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Nậm Chiến",
            "vi_do": 104.144442,
            "vi_tri_hanh_chinh": "xã Ngọc Chiến huyện Mường La tỉnh Sơn La",
            "von_dau_tu": 6.4e3
        },
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 220.0,
            "dung_tich": 2137.0,
            "kinh_do": 21.861172,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Nậm Mu",
            "nam_hoat_dong": "7/5/1905",
            "nam_khoi_cong": "6/28/1905",
            "quy_mo": "Lớn",
            "san_luong": 770.0,
            "ten_thuy_dien": "Bản Chát",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Nậm Mu",
            "vi_do": 103.828589,
            "vi_tri_hanh_chinh": "xã Mường Kim huyện Than Uyên tỉnh Lai Châu",
            "von_dau_tu": 9198.0
        },
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 520.0,
            "dung_tich": 184.2,
            "kinh_do": 21.696464,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Nậm Mu",
            "nam_hoat_dong": "5/1/2016",
            "nam_khoi_cong": "1/1/2006",
            "quy_mo": "Lớn",
            "san_luong": 1904.0,
            "ten_thuy_dien": "Huội Quảng",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Nậm Mu",
            "vi_do": 103.877603,
            "vi_tri_hanh_chinh": "xã Khoen On huyện Than Uyên & xã Chiềng Lao huyện Mường La tỉnh Sơn La",
            "von_dau_tu": 11082.0
        },
        {
            "chu_dau_tu": "Công ty cổ phần thủy điện Hủa Na",
            "cong_xuat": 180.0,
            "dung_tich": 5330.0,
            "kinh_do": 19.838131,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": "Chu",
            "nam_hoat_dong": "7/5/1905",
            "nam_khoi_cong": "7/2/1905",
            "quy_mo": "Lớn",
            "san_luong": 717.0,
            "ten_thuy_dien": "Hủa Na",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Chu",
            "vi_do": 105.084581,
            "vi_tri_hanh_chinh": "xã Đồng Văn huyện Quế Phong tỉnh Nghệ An",
            "von_dau_tu": 7065.0
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 320.0,
            "dung_tich": null,
            "kinh_do": 19.340428,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/2/1905",
            "nam_khoi_cong": "6/26/1905",
            "quy_mo": null,
            "san_luong": 1084.0,
            "ten_thuy_dien": "Bản Vẽ",
            "tinh_trang": null,
            "tren_song": "Sông Lam",
            "vi_do": 104.487347,
            "vi_tri_hanh_chinh": "xã Yên Na huyện Tương Dương tỉnh Nghệ An",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 100.0,
            "dung_tich": null,
            "kinh_do": 19.191111,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/5/1905",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": null,
            "san_luong": 442.8,
            "ten_thuy_dien": "Khe Bố",
            "tinh_trang": null,
            "tren_song": "Sông Lam",
            "vi_do": 104.658611,
            "vi_tri_hanh_chinh": "xã Tam Quang huyện Tương Dương tỉnh Nghệ An",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "Công ty TNHH MTV thủy điện Trung Sơn",
            "cong_xuat": 260.0,
            "dung_tich": 348.5,
            "kinh_do": 20.610103,
            "loai": "Có hồ chứa",
            "loai_hinh": "Trách nhiệm hữu hạn",
            "luu_vuc": "Mã",
            "nam_hoat_dong": "7/8/1905",
            "nam_khoi_cong": "7/4/1905",
            "quy_mo": "Lớn",
            "san_luong": 1018.0,
            "ten_thuy_dien": "Trung Sơn",
            "tinh_trang": "Đang xây dựng",
            "tren_song": "Sông Mã",
            "vi_do": 104.837458,
            "vi_tri_hanh_chinh": "xã Trung Sơn huyện Quan Hóa tỉnh Thanh Hóa",
            "von_dau_tu": 7775.0
        },
        {
            "chu_dau_tu": "Công ty cổ phần Công ty cổ phần Đầu tư và Xây dựng điện Hồi Xuân",
            "cong_xuat": 102.0,
            "dung_tich": 63.65,
            "kinh_do": 20.446374,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": "Mã",
            "nam_hoat_dong": "7/12/1905",
            "nam_khoi_cong": "3/1/2010",
            "quy_mo": "Lớn",
            "san_luong": 432.0,
            "ten_thuy_dien": "Hồi Xuân",
            "tinh_trang": "Đang xây dựng",
            "tren_song": "Sông Mã",
            "vi_do": 105.051508,
            "vi_tri_hanh_chinh": "xã Hồi Xuân và Thanh Xuân, huyện Quan Hóa tỉnh Thanh Hóa",
            "von_dau_tu": 3320.0
        },
        {
            "chu_dau_tu": "Công ty cổ phần Thủy điện Miền Trung",
            "cong_xuat": 170.0,
            "dung_tich": 60.2,
            "kinh_do": 16.230079,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": "A Sáp",
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": "Lớn",
            "san_luong": 690.0,
            "ten_thuy_dien": "A Lưới",
            "tinh_trang": "Đang vận hành",
            "tren_song": "A Sáp",
            "vi_do": 107.270151,
            "vi_tri_hanh_chinh": "xã Hồng Hạ huyện A Lưới tỉnh Thừa Thiên - Huế",
            "von_dau_tu": 3234.0
        },
        {
            "chu_dau_tu": "Công ty CP thủy điện A Vương",
            "cong_xuat": 210.0,
            "dung_tich": 343.55,
            "kinh_do": 15.799811,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": "A Vương",
            "nam_hoat_dong": "12/1/2008",
            "nam_khoi_cong": "8/1/2003",
            "quy_mo": "Lớn",
            "san_luong": 815.0,
            "ten_thuy_dien": "A Vương",
            "tinh_trang": "Đang vận hành",
            "tren_song": "A Vương",
            "vi_do": 107.617092,
            "vi_tri_hanh_chinh": "xã Mà Cooih huyện Đông Giang tỉnh Quảng Nam",
            "von_dau_tu": 3.8e3
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 100.0,
            "dung_tich": null,
            "kinh_do": 15.700021,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/9/1905",
            "nam_khoi_cong": "7/4/1905",
            "quy_mo": null,
            "san_luong": 420.0,
            "ten_thuy_dien": "Sông Bung 2",
            "tinh_trang": null,
            "tren_song": "Sông Bung",
            "vi_do": 107.486534,
            "vi_tri_hanh_chinh": "xã Zuôih và xã La Dêê huyện Nam Giang tỉnh Quảng Nam",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 156.0,
            "dung_tich": 510.0,
            "kinh_do": 15.725833,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Bung",
            "nam_hoat_dong": "7/7/1905",
            "nam_khoi_cong": "7/28/1900",
            "quy_mo": "Lớn",
            "san_luong": 586.0,
            "ten_thuy_dien": "Sông Bung 4",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Bung",
            "vi_do": 107.651175,
            "vi_tri_hanh_chinh": "xã Zuôih và Tà Pơơ huyện Nam Giang tỉnh Quảng Nam",
            "von_dau_tu": 5458.0
        },
        {
            "chu_dau_tu": "Tổng công ty Đầu tư phát triển đô thị và khu công nghiệp Việt Nam ",
            "cong_xuat": 190.0,
            "dung_tich": 312.0,
            "kinh_do": 15.458986,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Đăk Mi",
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": "Lớn",
            "san_luong": 752.0,
            "ten_thuy_dien": "Đăk Mi 4",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Đăk Mi",
            "vi_do": 107.912358,
            "vi_tri_hanh_chinh": "xã Phước Hiệp huyện Phước Sơn tỉnh Quảng Nam",
            "von_dau_tu": 4547.0
        },
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 190.0,
            "dung_tich": 733.4,
            "kinh_do": 15.331214,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "Thu Bồn",
            "nam_hoat_dong": "7/2/1905",
            "nam_khoi_cong": "6/28/1905",
            "quy_mo": "Lớn",
            "san_luong": 680.0,
            "ten_thuy_dien": "Sông Tranh 2",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Thu Bồn",
            "vi_do": 108.147781,
            "vi_tri_hanh_chinh": "xã Trà Tân huyện Bắc Trà My tỉnh Quảng Nam",
            "von_dau_tu": 4150.0
        },
        {
            "chu_dau_tu": "Cty Thủy điện An Khê - Ka Nak",
            "cong_xuat": 173.0,
            "dung_tich": 329.6,
            "kinh_do": 14.014833,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": " Ba",
            "nam_hoat_dong": "7/1/1905",
            "nam_khoi_cong": "11/1/2005",
            "quy_mo": "Lớn",
            "san_luong": 700.0,
            "ten_thuy_dien": "An Khê - Kanak",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Ba",
            "vi_do": 108.679575,
            "vi_tri_hanh_chinh": "huyện K'Bang và Tx. An Khê, tỉnh Gia Lai, huyện Tây Sơn tỉnh Bình Định",
            "von_dau_tu": 5616.0
        },
        {
            "chu_dau_tu": "Công ty Cổ phần Sông Ba Hạ",
            "cong_xuat": 220.0,
            "dung_tich": 395.0,
            "kinh_do": 13.022625,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": " Ba",
            "nam_hoat_dong": "11/1/2009",
            "nam_khoi_cong": "4/1/2004",
            "quy_mo": "Lớn",
            "san_luong": 835.0,
            "ten_thuy_dien": "Sông Ba Hạ",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sông Ba",
            "vi_do": 108.903872,
            "vi_tri_hanh_chinh": "xã Đức Bình Tây huyện Sông Hinh và xã Suối Trai huyện Sơn Hòa tỉnh Phú Yên",
            "von_dau_tu": 4275.0
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 100.0,
            "dung_tich": null,
            "kinh_do": 14.408347,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "5/1/2009",
            "nam_khoi_cong": "11/1/2003",
            "quy_mo": null,
            "san_luong": 417.0,
            "ten_thuy_dien": "Plei Krông",
            "tinh_trang": null,
            "tren_song": "Pô Kô",
            "vi_do": 107.863044,
            "vi_tri_hanh_chinh": "xã Sa Bình huyện Sa Thầy và xã Kroong Tp. Kon Tum tỉnh Kon Tum",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "Công ty thủy điện Ialy (thuộc EVN)",
            "cong_xuat": 720.0,
            "dung_tich": 1037.0,
            "kinh_do": 14.227369,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": " Sê San",
            "nam_hoat_dong": "6/24/1905",
            "nam_khoi_cong": "6/15/1905",
            "quy_mo": "Lớn",
            "san_luong": 3680.0,
            "ten_thuy_dien": "Ialy",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sê San",
            "vi_do": 107.829361,
            "vi_tri_hanh_chinh": "Tt. Ia Ly huyện Chư Păh tỉnh Gia Lai",
            "von_dau_tu": 8.3e3
        },
        {
            "chu_dau_tu": "Công ty thủy điện Ialy (thuộc EVN)",
            "cong_xuat": 260.0,
            "dung_tich": 92.0,
            "kinh_do": 14.215164,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": " Sê San",
            "nam_hoat_dong": "6/28/1905",
            "nam_khoi_cong": "6/24/1905",
            "quy_mo": "Lớn",
            "san_luong": 221.0,
            "ten_thuy_dien": "Sê San 3",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sê San",
            "vi_do": 107.722164,
            "vi_tri_hanh_chinh": "huyện Chư Păh tỉnh Gia Lai",
            "von_dau_tu": 4.0e3
        },
        {
            "chu_dau_tu": "Công ty cổ phần thủy điện thuỷ điện Sê San 3A",
            "cong_xuat": 108.0,
            "dung_tich": 80.6,
            "kinh_do": 14.106311,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": " Sê San",
            "nam_hoat_dong": "6/1/2007",
            "nam_khoi_cong": "4/1/2003",
            "quy_mo": "Lớn",
            "san_luong": 479.0,
            "ten_thuy_dien": "Sê San 3A",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sê San",
            "vi_do": 107.657672,
            "vi_tri_hanh_chinh": "xã Mô Rai huyện Sa Thầy tỉnh Kon Tum và xã Ia Krai huyện Ia Grai tỉnh Gia \nLai",
            "von_dau_tu": 1945.0
        },
        {
            "chu_dau_tu": "Công ty phát triển thủy điện sê san",
            "cong_xuat": 360.0,
            "dung_tich": 893.3,
            "kinh_do": 13.967831,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": " Sê San",
            "nam_hoat_dong": "7/1/1905",
            "nam_khoi_cong": "6/26/1905",
            "quy_mo": "Lớn",
            "san_luong": 1042.0,
            "ten_thuy_dien": "Sê San 4",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sê San",
            "vi_do": 107.495328,
            "vi_tri_hanh_chinh": "xã Mô Rai huyện Sa Thầy tỉnh Kon Tum & xã Ia O huyện Ia Grai tỉnh Gia Lai",
            "von_dau_tu": 5.8e3
        },
        {
            "chu_dau_tu": "Tập đoàn Điện lực Việt Nam (EVN)",
            "cong_xuat": 280.0,
            "dung_tich": 63.24,
            "kinh_do": 12.530467,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": " Srêpôk",
            "nam_hoat_dong": "7/3/1905",
            "nam_khoi_cong": "6/25/1905",
            "quy_mo": "Lớn",
            "san_luong": 1105.0,
            "ten_thuy_dien": "Buôn Kuốp",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Sêrêpôk",
            "vi_do": 107.924325,
            "vi_tri_hanh_chinh": "xã Nam Đà huyện Krông Nô, tỉnh Đăk Nông & xã Dray Sáp huyện Krông Ana tỉnh Đắk \nLắk",
            "von_dau_tu": 4616.0
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 220.0,
            "dung_tich": null,
            "kinh_do": 12.752433,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/1/1905",
            "nam_khoi_cong": "6/27/1905",
            "quy_mo": null,
            "san_luong": 1060.0,
            "ten_thuy_dien": "Sêrêpôk 3",
            "tinh_trang": null,
            "tren_song": "Sêrêpôk",
            "vi_do": 107.876758,
            "vi_tri_hanh_chinh": "xã Ea Nuôl và Tân Hòa huyện Buôn Đôn tỉnh Đăk Lăk và xã Ea Pô huyện Cư Jút \ntỉnh Đăk Nông",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "Công ty Cổ phần thủy điện Vĩnh Sơn-Sông Hinh",
            "cong_xuat": 220.0,
            "dung_tich": 145.52,
            "kinh_do": 14.694139,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": "Đắk Snghé ",
            "nam_hoat_dong": "3/1/2020",
            "nam_khoi_cong": "9/1/2009",
            "quy_mo": "Lớn",
            "san_luong": 1094.0,
            "ten_thuy_dien": "Thượng Kon Tum",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Đăk Snghé",
            "vi_do": 108.229889,
            "vi_tri_hanh_chinh": "xã Đăk Kôi huyện Kon Rẫy và xã Đăk Tăng huyện Kon Plông tỉnh Kon Tum",
            "von_dau_tu": 5744.0
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 125.0,
            "dung_tich": null,
            "kinh_do": 14.978447,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/6/1905",
            "nam_khoi_cong": "2/1/2008",
            "quy_mo": null,
            "san_luong": 520.0,
            "ten_thuy_dien": "Đăk Đrinh",
            "tinh_trang": null,
            "tren_song": "Đăk Đrinh",
            "vi_do": 108.301314,
            "vi_tri_hanh_chinh": "xã Sơn Dung và Sơn Mùa huyện Sơn Tây tỉnh Quảng Ngãi",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 225.0,
            "dung_tich": null,
            "kinh_do": 11.857767,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/9/1905",
            "nam_khoi_cong": "6/13/1905",
            "quy_mo": null,
            "san_luong": 662.0,
            "ten_thuy_dien": "Thác Mơ (*)",
            "tinh_trang": null,
            "tren_song": "Sông Bé",
            "vi_do": 107.019253,
            "vi_tri_hanh_chinh": "xã Đức Hạnh huyện Bù Gia Mập tỉnh Bình Phước",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "Công ty CP Thuỷ điện Đa Nhim - Hàm Thuận - Đa Mi",
            "cong_xuat": 160.0,
            "dung_tich": 165.0,
            "kinh_do": 11.852897,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": " Đa Nhim",
            "nam_hoat_dong": "5/17/1905",
            "nam_khoi_cong": "5/15/1905",
            "quy_mo": "Lớn",
            "san_luong": 1.0e3,
            "ten_thuy_dien": "Đa Nhim",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Đa Nhim",
            "vi_do": 108.605836,
            "vi_tri_hanh_chinh": "Tt. D'Ran huyện Đơn Dương tỉnh Lâm Đồng và xã Lâm Sơn huyện Ninh Sơn tỉnh Ninh \nThuận",
            "von_dau_tu": 0.0
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 300.0,
            "dung_tich": null,
            "kinh_do": 11.649864,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/30/1905",
            "nam_khoi_cong": "6/25/1905",
            "quy_mo": null,
            "san_luong": 1178.0,
            "ten_thuy_dien": "Đại Ninh",
            "tinh_trang": null,
            "tren_song": "Đa Nhim",
            "vi_do": 108.320239,
            "vi_tri_hanh_chinh": "huyện Đức Trọng tỉnh Lâm Đồng & huyện Bắc Bình tỉnh ‎Bình Thuận",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "Tập đoàn Điện lực Việt Nam (EVN)",
            "cong_xuat": 180.0,
            "dung_tich": 1423.6,
            "kinh_do": 11.872225,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": " Đồng Nai",
            "nam_hoat_dong": "7/3/1905",
            "nam_khoi_cong": "6/26/1905",
            "quy_mo": "Lớn",
            "san_luong": 607.0,
            "ten_thuy_dien": "Đồng Nai 3",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Đồng Nai",
            "vi_do": 107.888656,
            "vi_tri_hanh_chinh": "xã Đắk Plao huyện Đắk Glong tỉnh Đăk Nông và xã Lộc Lâm huyện Bảo Lâm, tỉnh Lâm \nĐồng",
            "von_dau_tu": 5.1e3
        },
        {
            "chu_dau_tu": "EVN",
            "cong_xuat": 340.0,
            "dung_tich": 337.2,
            "kinh_do": 11.885128,
            "loai": "Có hồ chứa",
            "loai_hinh": "Cổ phần",
            "luu_vuc": " Đồng Nai",
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "6/26/1905",
            "quy_mo": "Lớn",
            "san_luong": 1.1e3,
            "ten_thuy_dien": "Đồng Nai 4",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Đồng Nai",
            "vi_do": 107.728639,
            "vi_tri_hanh_chinh": "Tt. Quảng Khê huyện Đăk GLong tỉnh Đăk Nông và xã Lộc Bảo huyện Bảo Lâm \ntỉnh Lâm Đồng",
            "von_dau_tu": 4.7e3
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 150.0,
            "dung_tich": null,
            "kinh_do": 11.792692,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/7/1905",
            "nam_khoi_cong": "7/4/1905",
            "quy_mo": null,
            "san_luong": 616.0,
            "ten_thuy_dien": "Đồng Nai 5",
            "tinh_trang": null,
            "tren_song": "Đồng Nai",
            "vi_do": 107.553364,
            "vi_tri_hanh_chinh": "xã Đắk Sin huyện Đăk R'Lấp tỉnh Đăk Nông và xã Lộc Bắc huyện Bảo Lâm tỉnh Lâm \nĐồng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": "Công ty thủy điện Trị An (thuộc EVN)",
            "cong_xuat": 400.0,
            "dung_tich": 2765.0,
            "kinh_do": 11.104786,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": " Đồng Nai",
            "nam_hoat_dong": "6/13/1905",
            "nam_khoi_cong": "6/6/1905",
            "quy_mo": "Lớn",
            "san_luong": 1.7e3,
            "ten_thuy_dien": "Trị An",
            "tinh_trang": "Đang vận hành",
            "tren_song": "Đồng Nai",
            "vi_do": 106.984822,
            "vi_tri_hanh_chinh": "huyện Vĩnh Cửu tỉnh Đồng Nai",
            "von_dau_tu": 0.0
        },
        {
            "chu_dau_tu": "Công ty Thủy điện Đa Nhim – Hàm Thuận – Đa Mi",
            "cong_xuat": 475.0,
            "dung_tich": 836.0,
            "kinh_do": 11.335956,
            "loai": "Có hồ chứa",
            "loai_hinh": "Nhà nước",
            "luu_vuc": "La Ngà",
            "nam_hoat_dong": "6/23/1905",
            "nam_khoi_cong": "6/19/1905",
            "quy_mo": "Lớn",
            "san_luong": 1555.0,
            "ten_thuy_dien": "Hàm Thuận - Đa Mi",
            "tinh_trang": "Đang vận hành",
            "tren_song": "La Ngà",
            "vi_do": 107.934956,
            "vi_tri_hanh_chinh": "xã La Ngâu huyện Tánh Linh và\nLa Dạ huyện Hàm Thuận Bắc tỉnh ‎Bình Thuận",
            "von_dau_tu": 0.0
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 144.0,
            "dung_tich": null,
            "kinh_do": 11.96642,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/3/1905",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": null,
            "san_luong": 637.0,
            "ten_thuy_dien": "Đăk R’Tih",
            "tinh_trang": null,
            "tren_song": "Đăk R’tih",
            "vi_do": 107.657365,
            "vi_tri_hanh_chinh": "Tx. Gia Nghĩa và xã Nhân Cơ huyện Đăk R’lấp tỉnh Đăk Nông",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 42.0,
            "dung_tich": null,
            "kinh_do": 22.45103,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/6/1905",
            "nam_khoi_cong": "7/2/1905",
            "quy_mo": null,
            "san_luong": 166.2,
            "ten_thuy_dien": "Sông Bạc",
            "tinh_trang": null,
            "tren_song": "Sông Bạc",
            "vi_do": 104.721281,
            "vi_tri_hanh_chinh": "xã Tân Trịnh huyện Quang Bình tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 5.0,
            "dung_tich": null,
            "kinh_do": 22.484501,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": null,
            "nam_khoi_cong": null,
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Xuân Minh HG",
            "tinh_trang": null,
            "tren_song": "Sông Bạc",
            "vi_do": 104.736918,
            "vi_tri_hanh_chinh": "xã Xuân Minh huyện Quang Bình tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 17.0,
            "dung_tich": null,
            "kinh_do": 22.504828,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/8/1905",
            "nam_khoi_cong": "7/6/1905",
            "quy_mo": null,
            "san_luong": 70.0,
            "ten_thuy_dien": "Bắc Nà",
            "tinh_trang": null,
            "tren_song": "Bắc Nà",
            "vi_do": 104.33611,
            "vi_tri_hanh_chinh": "xã Thải Giàng Phố và Bản Liền huyện Bắc Hà tỉnh Lào Cai",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 14.0,
            "dung_tich": null,
            "kinh_do": 22.73944,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/3/1905",
            "nam_khoi_cong": "7/9/1905",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Sông Chảy 3",
            "tinh_trang": null,
            "tren_song": "Sông Chảy",
            "vi_do": 104.63,
            "vi_tri_hanh_chinh": "xã Tụ Nhân & Pờ Ly Ngài huyện Hoàng Su Phì tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 16.0,
            "dung_tich": null,
            "kinh_do": 22.714756,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "7/2/1905",
            "quy_mo": null,
            "san_luong": 62.0,
            "ten_thuy_dien": "Sông Chảy 5",
            "tinh_trang": null,
            "tren_song": "Sông Chảy",
            "vi_do": 104.53495,
            "vi_tri_hanh_chinh": "xã Thèn Phàng và Ngán Chiên huyện Xín Mần tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 16.0,
            "dung_tich": null,
            "kinh_do": 22.691463,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "2/1/2019",
            "nam_khoi_cong": "2/1/2017",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Sông Chảy 6",
            "tinh_trang": null,
            "tren_song": "Sông Chảy",
            "vi_do": 104.462924,
            "vi_tri_hanh_chinh": "Tt. Cốc Pài và xã Thèn Phàng huyện Xín Mần tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 26.0,
            "dung_tich": null,
            "kinh_do": 22.68762,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/10/1905",
            "nam_khoi_cong": "7/8/1905",
            "quy_mo": null,
            "san_luong": 96.4,
            "ten_thuy_dien": "Pa Ke",
            "tinh_trang": null,
            "tren_song": "Sông Chảy",
            "vi_do": 104.336418,
            "vi_tri_hanh_chinh": "xã Lùng Sui huyện Si Ma Cai tỉnh Lào Cai & xã Pà Vầy Sủ huyện Xín Mần tỉnh Hà \nGiang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 90.0,
            "dung_tich": null,
            "kinh_do": 22.508545,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "6/27/1905",
            "quy_mo": null,
            "san_luong": 378.0,
            "ten_thuy_dien": "Bắc Hà\n(Cốc Ly)",
            "tinh_trang": null,
            "tren_song": "Sông Chảy",
            "vi_do": 104.197144,
            "vi_tri_hanh_chinh": "xã Cốc Ly huyện Bắc Hà tỉnh Lào Cai",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 21.0,
            "dung_tich": null,
            "kinh_do": 22.303611,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/8/1905",
            "nam_khoi_cong": "7/5/1905",
            "quy_mo": null,
            "san_luong": 89.0,
            "ten_thuy_dien": "Vĩnh Hà",
            "tinh_trang": null,
            "tren_song": "Sông Chảy",
            "vi_do": 104.453333,
            "vi_tri_hanh_chinh": "xã Tân Dương & Thượng Hà huyện Bảo Yên tỉnh Lào Cai",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 19.5,
            "dung_tich": null,
            "kinh_do": 22.429486,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/3/1905",
            "nam_khoi_cong": "6/30/1905",
            "quy_mo": null,
            "san_luong": 70.0,
            "ten_thuy_dien": "Sông Chừng",
            "tinh_trang": null,
            "tren_song": "Sông Con",
            "vi_do": 104.63307,
            "vi_tri_hanh_chinh": "Tt. Yên Bình huyện Quang Bình tỉnh Hà Giang[2]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 30.0,
            "dung_tich": null,
            "kinh_do": 22.961208,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/14/1905",
            "nam_khoi_cong": "7/12/1905",
            "quy_mo": null,
            "san_luong": 170.0,
            "ten_thuy_dien": "Bảo Lạc A",
            "tinh_trang": null,
            "tren_song": "Sông Gâm",
            "vi_do": 105.775194,
            "vi_tri_hanh_chinh": "xã Cô Ba huyện Bảo Lạc tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 18.0,
            "dung_tich": null,
            "kinh_do": 22.946887,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/1/2020",
            "nam_khoi_cong": "7/9/1905",
            "quy_mo": null,
            "san_luong": 35.3,
            "ten_thuy_dien": "Bảo Lạc B",
            "tinh_trang": null,
            "tren_song": "Sông Gâm",
            "vi_do": 105.595266,
            "vi_tri_hanh_chinh": "xã Bảo Toàn huyện Bảo Lạc tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 30.0,
            "dung_tich": null,
            "kinh_do": 22.942286,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "12/1/2016",
            "nam_khoi_cong": "11/1/2014",
            "quy_mo": null,
            "san_luong": 124.0,
            "ten_thuy_dien": "Bảo Lâm 1",
            "tinh_trang": null,
            "tren_song": "Sông Gâm",
            "vi_do": 105.548844,
            "vi_tri_hanh_chinh": "xã Lý Bôn huyện Bảo Lâm tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 30.0,
            "dung_tich": null,
            "kinh_do": 22.855687,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/11/1905",
            "nam_khoi_cong": "7/9/1905",
            "quy_mo": null,
            "san_luong": 110.0,
            "ten_thuy_dien": "Mông Ân",
            "tinh_trang": null,
            "tren_song": "Sông Gâm",
            "vi_do": 105.485566,
            "vi_tri_hanh_chinh": "Tt. Pác Miầu và xã Nam Quang huyện Bảo Lâm tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 45.0,
            "dung_tich": null,
            "kinh_do": 22.757626,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/9/1905",
            "nam_khoi_cong": "7/6/1905",
            "quy_mo": null,
            "san_luong": 197.0,
            "ten_thuy_dien": "Bắc Mê",
            "tinh_trang": null,
            "tren_song": "Sông Gâm",
            "vi_do": 105.429388,
            "vi_tri_hanh_chinh": "xã Yên Phong & Phú Nam huyện Bắc Mê tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 48.0,
            "dung_tich": null,
            "kinh_do": 22.198333,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/5/1905",
            "nam_khoi_cong": "7/1/1905",
            "quy_mo": null,
            "san_luong": 198.6,
            "ten_thuy_dien": "Chiêm Hóa",
            "tinh_trang": null,
            "tren_song": "Sông Gâm",
            "vi_do": 105.328056,
            "vi_tri_hanh_chinh": "xã Ngọc Hội huyện Chiêm Hóa tỉnh Tuyên Quang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 90.0,
            "dung_tich": null,
            "kinh_do": 21.996966,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/12/1905",
            "nam_khoi_cong": "7/5/1905",
            "quy_mo": null,
            "san_luong": 296.0,
            "ten_thuy_dien": "Yên Sơn",
            "tinh_trang": null,
            "tren_song": "Sông Gâm",
            "vi_do": 105.216218,
            "vi_tri_hanh_chinh": "xã Quý Quân huyện Yên Sơn tỉnh Tuyên Quang[3]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 12.0,
            "dung_tich": null,
            "kinh_do": 22.962039,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": null,
            "nam_khoi_cong": "7/9/1905",
            "quy_mo": null,
            "san_luong": 42.0,
            "ten_thuy_dien": "Nậm Lang",
            "tinh_trang": null,
            "tren_song": "Nậm Lang",
            "vi_do": 105.265238,
            "vi_tri_hanh_chinh": "xã Ngọc Long huyện Yên Minh tỉnh Hà Giang[4]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 18.0,
            "dung_tich": null,
            "kinh_do": 22.838338,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": null,
            "nam_khoi_cong": "7/9/1905",
            "quy_mo": null,
            "san_luong": 63.2,
            "ten_thuy_dien": "Phong Quang",
            "tinh_trang": null,
            "tren_song": "Sông Lô",
            "vi_do": 104.973367,
            "vi_tri_hanh_chinh": "p. Quang Trung Tp. Hà Giang[4]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 28.0,
            "dung_tich": null,
            "kinh_do": 22.724898,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/10/1905",
            "nam_khoi_cong": "10/1/2015",
            "quy_mo": null,
            "san_luong": 117.0,
            "ten_thuy_dien": "Sông Lô 2",
            "tinh_trang": null,
            "tren_song": "Sông Lô",
            "vi_do": 104.972595,
            "vi_tri_hanh_chinh": "xã Đạo Đức và Trung Thành huyện Vị Xuyên tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 18.0,
            "dung_tich": null,
            "kinh_do": 22.66113,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": null,
            "nam_khoi_cong": "7/3/1905",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Sông Lô 3",
            "tinh_trang": null,
            "tren_song": "Sông Lô",
            "vi_do": 104.993551,
            "vi_tri_hanh_chinh": "Tt. Vị Xuyên và xã Ngọc Linh huyện Vị Xuyên tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 24.0,
            "dung_tich": null,
            "kinh_do": 22.544846,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/9/1905",
            "nam_khoi_cong": "7/7/1905",
            "quy_mo": null,
            "san_luong": 80.0,
            "ten_thuy_dien": "Sông Lô 4",
            "tinh_trang": null,
            "tren_song": "Sông Lô",
            "vi_do": 104.911361,
            "vi_tri_hanh_chinh": "xã Tân Thành huyện Bắc Quang tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 29.7,
            "dung_tich": null,
            "kinh_do": null,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": null,
            "nam_khoi_cong": "7/12/1905",
            "quy_mo": null,
            "san_luong": 115.8,
            "ten_thuy_dien": "Sông Lô 5",
            "tinh_trang": null,
            "tren_song": "Sông Lô",
            "vi_do": null,
            "vi_tri_hanh_chinh": "xã Quang Minh & Kim Ngọc huyện Bắc Quang tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 48.0,
            "dung_tich": null,
            "kinh_do": 22.296175,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/1/2020",
            "nam_khoi_cong": "9/1/2015",
            "quy_mo": null,
            "san_luong": 187.2,
            "ten_thuy_dien": "Sông Lô 6",
            "tinh_trang": null,
            "tren_song": "Sông Lô",
            "vi_do": 104.917122,
            "vi_tri_hanh_chinh": "xã Vĩnh Hảo huyện Bắc Quang tỉnh Hà Giang và xã Yên Thuận huyện Hàm Yên \ntỉnh Tuyên Quang[5].",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 18.0,
            "dung_tich": null,
            "kinh_do": 21.35565,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/7/1905",
            "nam_khoi_cong": "7/3/1905",
            "quy_mo": null,
            "san_luong": 70.0,
            "ten_thuy_dien": "Nậm Hóa 1",
            "tinh_trang": null,
            "tren_song": "Nậm Hua",
            "vi_do": 103.407597,
            "vi_tri_hanh_chinh": "xã Mường Bám huyện Thuận Châu tỉnh Sơn La",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 27.0,
            "dung_tich": null,
            "kinh_do": 22.064808,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/1/2020",
            "nam_khoi_cong": "7/10/1905",
            "quy_mo": null,
            "san_luong": 106.6,
            "ten_thuy_dien": "Sông Lô 8A",
            "tinh_trang": null,
            "tren_song": "Sông Lô",
            "vi_do": 105.05638,
            "vi_tri_hanh_chinh": "Tt. Tân Yên và xã Tân Thành huyện Hàm Yên tỉnh Tuyên Quang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 27.0,
            "dung_tich": null,
            "kinh_do": 21.906929,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "11/1/2020",
            "nam_khoi_cong": "7/10/1905",
            "quy_mo": null,
            "san_luong": 109.1,
            "ten_thuy_dien": "Sông Lô 8B",
            "tinh_trang": null,
            "tren_song": "Sông Lô",
            "vi_do": 105.174717,
            "vi_tri_hanh_chinh": "xã Thắng Quân & Phúc Ninh huyện Yên Sơn tỉnh Tuyên Quang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 24.0,
            "dung_tich": null,
            "kinh_do": 21.341211,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": null,
            "nam_khoi_cong": "7/1/1905",
            "quy_mo": null,
            "san_luong": 100.0,
            "ten_thuy_dien": "Nậm Lúc",
            "tinh_trang": null,
            "tren_song": "Nậm Lúc",
            "vi_do": 104.3498,
            "vi_tri_hanh_chinh": "xã Nậm Lúc và Cốc Lầu huyện Bắc Hà tỉnh Lào Cai",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 5.1,
            "dung_tich": null,
            "kinh_do": 22.556391,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "10/1/2017",
            "nam_khoi_cong": "2/1/2009",
            "quy_mo": null,
            "san_luong": 22.6,
            "ten_thuy_dien": "Nậm Ly",
            "tinh_trang": null,
            "tren_song": "Nậm Ly",
            "vi_do": 104.569684,
            "vi_tri_hanh_chinh": "xã Quảng Nguyên huyện Xín Mần tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 18.0,
            "dung_tich": null,
            "kinh_do": 22.89566,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/10/1905",
            "nam_khoi_cong": "7/7/1905",
            "quy_mo": null,
            "san_luong": 72.0,
            "ten_thuy_dien": "Nậm Mạ",
            "tinh_trang": null,
            "tren_song": "Nậm Mạ",
            "vi_do": 105.07815,
            "vi_tri_hanh_chinh": "xã Tùng Bá huyện Vị Xuyên tỉnh Hà Giang[6]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 6.0,
            "dung_tich": null,
            "kinh_do": 23.156976,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "10/1/2011",
            "nam_khoi_cong": "4/1/2009",
            "quy_mo": null,
            "san_luong": 25.0,
            "ten_thuy_dien": "Sông Miện 1",
            "tinh_trang": null,
            "tren_song": "Sông Miện",
            "vi_do": 105.017348,
            "vi_tri_hanh_chinh": "xã Bát Đại Sơn huyện Quản Bạ và xã Na Khê huyện Yên Minh tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 82.0,
            "dung_tich": null,
            "kinh_do": 22.998902,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "9/1/2010",
            "nam_khoi_cong": "6/30/1905",
            "quy_mo": null,
            "san_luong": 400.0,
            "ten_thuy_dien": "Thái An",
            "tinh_trang": null,
            "tren_song": "Sông Miện",
            "vi_do": 105.065431,
            "vi_tri_hanh_chinh": "xã Thái An huyện Quản Bạ tỉnh Hà Giang[7].",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 38.0,
            "dung_tich": null,
            "kinh_do": 22.960782,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/1/2017",
            "nam_khoi_cong": "7/6/1905",
            "quy_mo": null,
            "san_luong": 160.0,
            "ten_thuy_dien": "Thuận Hòa",
            "tinh_trang": null,
            "tren_song": "Sông Miện",
            "vi_do": 105.033318,
            "vi_tri_hanh_chinh": "xã Thuận Hòa huyện Vị Xuyên tỉnh Hà Giang[8]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 16.5,
            "dung_tich": null,
            "kinh_do": 22.923324,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": null,
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Sông Miện 5",
            "tinh_trang": null,
            "tren_song": "Sông Miện",
            "vi_do": 105.006382,
            "vi_tri_hanh_chinh": "xã Thuận Hòa huyện Vị Xuyên tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 9.0,
            "dung_tich": null,
            "kinh_do": 22.893316,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "3/1/2015",
            "nam_khoi_cong": "3/1/2011",
            "quy_mo": null,
            "san_luong": 35.0,
            "ten_thuy_dien": "Sông Miện 5A",
            "tinh_trang": null,
            "tren_song": "Sông Miện",
            "vi_do": 104.99225,
            "vi_tri_hanh_chinh": "xã Thuận Hòa huyện Vị Xuyên tỉnh Hà Giang[9]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 12.0,
            "dung_tich": null,
            "kinh_do": 22.848615,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "3/1/2017",
            "nam_khoi_cong": null,
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Sông Miện 6",
            "tinh_trang": null,
            "tren_song": "Sông Miện",
            "vi_do": 105.013571,
            "vi_tri_hanh_chinh": "p. Quang Trung Tp. Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 12.0,
            "dung_tich": null,
            "kinh_do": 22.549631,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/26/1905",
            "nam_khoi_cong": "6/24/1905",
            "quy_mo": null,
            "san_luong": 56.0,
            "ten_thuy_dien": "Nậm Mu",
            "tinh_trang": null,
            "tren_song": "Nậm Mu",
            "vi_do": 104.87675,
            "vi_tri_hanh_chinh": "xã Tân Thành huyện Bắc Quang tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 13.5,
            "dung_tich": null,
            "kinh_do": 22.612182,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/1/1905",
            "nam_khoi_cong": "6/27/1905",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Nậm Ngần",
            "tinh_trang": null,
            "tren_song": "Nậm Ngần",
            "vi_do": 104.893062,
            "vi_tri_hanh_chinh": "xã Thượng Sơn & Quảng Ngần huyện Vị Xuyên tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 10.0,
            "dung_tich": null,
            "kinh_do": 23.04135,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "11/1/2021",
            "nam_khoi_cong": "9/1/2019",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Sông Nhiệm 3",
            "tinh_trang": null,
            "tren_song": "Sông Nhiệm",
            "vi_do": 105.406101,
            "vi_tri_hanh_chinh": "xã Niêm Sơn huyện Mèo Vạc tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 6.0,
            "dung_tich": null,
            "kinh_do": 23.011508,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "11/1/2021",
            "nam_khoi_cong": "6/1/2018",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Sông Nhiệm 4",
            "tinh_trang": null,
            "tren_song": "Sông Nhiệm",
            "vi_do": 105.474624,
            "vi_tri_hanh_chinh": "xã Niêm Tòng huyện Mèo Vạc tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 32.0,
            "dung_tich": null,
            "kinh_do": 23.231101,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/9/1905",
            "nam_khoi_cong": "7/5/1905",
            "quy_mo": null,
            "san_luong": 129.0,
            "ten_thuy_dien": "Nho Quế 1",
            "tinh_trang": null,
            "tren_song": "Nho Quế",
            "vi_do": 105.427198,
            "vi_tri_hanh_chinh": "xã Giàng Chu Phìn và Xín Cái huyện Mèo Vạc tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 48.0,
            "dung_tich": null,
            "kinh_do": 23.181384,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "8/1/2016",
            "nam_khoi_cong": "8/1/2012",
            "quy_mo": null,
            "san_luong": 225.0,
            "ten_thuy_dien": "Nho Quế 2",
            "tinh_trang": null,
            "tren_song": "Nho Quế",
            "vi_do": 105.477844,
            "vi_tri_hanh_chinh": "xã Giàng Chu Phìn và Xín Cái huyện Mèo Vạc tỉnh Hà Giang",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 46.0,
            "dung_tich": null,
            "kinh_do": 23.013075,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/1/2018",
            "nam_khoi_cong": "7/1/2015",
            "quy_mo": null,
            "san_luong": 192.2,
            "ten_thuy_dien": "Bảo Lâm 3",
            "tinh_trang": null,
            "tren_song": "Nho Quế",
            "vi_do": 105.486747,
            "vi_tri_hanh_chinh": "xã Đức Hạnh huyện Bảo Lâm tỉnh Cao Bằng và xã Niêm Tòng huyện Mèo Vạc tỉnh Hà \nGiang[10]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 8.0,
            "dung_tich": null,
            "kinh_do": null,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/1/2018",
            "nam_khoi_cong": "2/1/2016",
            "quy_mo": null,
            "san_luong": 33.4,
            "ten_thuy_dien": "Bảo Lâm 3A",
            "tinh_trang": null,
            "tren_song": "Nho Quế",
            "vi_do": null,
            "vi_tri_hanh_chinh": "xã Đức Hạnh và Lý Bôn huyện Bảo Lâm tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 12.0,
            "dung_tich": null,
            "kinh_do": 22.487111,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": null,
            "san_luong": 48.9,
            "ten_thuy_dien": "Nậm Khánh",
            "tinh_trang": null,
            "tren_song": "Nậm Phàng",
            "vi_do": 104.366694,
            "vi_tri_hanh_chinh": "xã Nậm Khánh và Bản Liền huyện Bắc Hà tỉnh Lào Cai",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 36.0,
            "dung_tich": null,
            "kinh_do": 22.41566,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "6/30/1905",
            "quy_mo": null,
            "san_luong": 146.0,
            "ten_thuy_dien": "Nậm Phàng",
            "tinh_trang": null,
            "tren_song": "Nậm Phàng",
            "vi_do": 104.318392,
            "vi_tri_hanh_chinh": "xã Nậm Đét và Nậm Khánh huyện Bắc Hà tỉnh Lào Cai[11]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 16.0,
            "dung_tich": null,
            "kinh_do": 22.171324,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/8/1905",
            "nam_khoi_cong": "6/30/1905",
            "quy_mo": null,
            "san_luong": 65.3,
            "ten_thuy_dien": "Thác Xăng",
            "tinh_trang": null,
            "tren_song": "Bắc Giang",
            "vi_do": 106.498572,
            "vi_tri_hanh_chinh": "xã Hùng Việt huyện Tràng Định tỉnh Lạng Sơn[12]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 6.0,
            "dung_tich": null,
            "kinh_do": 22.73418,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "12/1/2018",
            "nam_khoi_cong": "5/1/2016",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Thân Giáp",
            "tinh_trang": null,
            "tren_song": "Bắc Vọng",
            "vi_do": 106.547782,
            "vi_tri_hanh_chinh": "xã Đoài Dương huyện Trùng Khánh tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 6.0,
            "dung_tich": null,
            "kinh_do": 22.684633,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "6/28/1905",
            "nam_khoi_cong": null,
            "quy_mo": null,
            "san_luong": 30.0,
            "ten_thuy_dien": "Nà Lòa",
            "tinh_trang": null,
            "tren_song": "Bắc Vọng",
            "vi_do": 106.599022,
            "vi_tri_hanh_chinh": "xã Bế Văn Đàn huyện Phục Hòa tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 6.0,
            "dung_tich": null,
            "kinh_do": 22.672175,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "1/1/2014",
            "nam_khoi_cong": "7/5/1905",
            "quy_mo": null,
            "san_luong": 18.5,
            "ten_thuy_dien": "Nà Tẩu",
            "tinh_trang": null,
            "tren_song": "Bắc Vọng",
            "vi_do": 106.504972,
            "vi_tri_hanh_chinh": "xã Cai Bộ huyện Quảng Hòa tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 16.5,
            "dung_tich": null,
            "kinh_do": 22.570529,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/11/1905",
            "nam_khoi_cong": "7/1/1905",
            "quy_mo": null,
            "san_luong": 49.0,
            "ten_thuy_dien": "Tiên Thành",
            "tinh_trang": null,
            "tren_song": "Sông Bằng",
            "vi_do": 106.433418,
            "vi_tri_hanh_chinh": "xã Tiên Thành huyện Phục Hòa tỉnh Cao Bằng[13]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 17.4,
            "dung_tich": null,
            "kinh_do": 22.54283,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/10/1905",
            "nam_khoi_cong": "9/1/2009",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Hòa Thuận",
            "tinh_trang": null,
            "tren_song": "Sông Bằng",
            "vi_do": 106.494385,
            "vi_tri_hanh_chinh": "Tt. Hòa Thuận huyện Quảng Hòatỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 6.5,
            "dung_tich": null,
            "kinh_do": 22.734798,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/13/1905",
            "nam_khoi_cong": "7/12/1905",
            "quy_mo": null,
            "san_luong": 20.9,
            "ten_thuy_dien": "Bình Long",
            "tinh_trang": null,
            "tren_song": "Dẻ Rào",
            "vi_do": 106.122213,
            "vi_tri_hanh_chinh": "xã Bình Long huyện Hòa An tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 5.8,
            "dung_tich": null,
            "kinh_do": 22.619159,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "9/1/2018",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": null,
            "san_luong": 23.3,
            "ten_thuy_dien": "Hoa Thám",
            "tinh_trang": null,
            "tren_song": "Sông Hiến",
            "vi_do": 106.100172,
            "vi_tri_hanh_chinh": "xã Hoa Thám huyện Nguyên Bình tỉnh Cao Bằng[14]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 5.0,
            "dung_tich": null,
            "kinh_do": 22.597833,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/12/1905",
            "nam_khoi_cong": "7/9/1905",
            "quy_mo": null,
            "san_luong": 17.0,
            "ten_thuy_dien": "Bạch Đằng",
            "tinh_trang": null,
            "tren_song": "Sông Hiến",
            "vi_do": 106.163859,
            "vi_tri_hanh_chinh": "xã Bạch Đằng huyện Hòa An tỉnh Cao Bằng[15]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 6.0,
            "dung_tich": null,
            "kinh_do": 22.212974,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/12/1905",
            "nam_khoi_cong": "4/1/2019",
            "quy_mo": null,
            "san_luong": null,
            "ten_thuy_dien": "Pác Cáp",
            "tinh_trang": null,
            "tren_song": "Na Rì",
            "vi_do": 106.130434,
            "vi_tri_hanh_chinh": "xã Lương Thành và Văn Minh huyện Na Rì tỉnh Bắc Kạn[16]",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 18.0,
            "dung_tich": null,
            "kinh_do": 22.85895,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "6/29/1905",
            "quy_mo": null,
            "san_luong": 70.0,
            "ten_thuy_dien": "Bản Rạ",
            "tinh_trang": null,
            "tren_song": "Quây Sơn",
            "vi_do": 106.699769,
            "vi_tri_hanh_chinh": "xã Đàm Thủy huyện Trùng Khánh tỉnh Cao Bằng",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 30.0,
            "dung_tich": null,
            "kinh_do": 22.290999,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/11/1905",
            "nam_khoi_cong": "7/8/1905",
            "quy_mo": null,
            "san_luong": 125.0,
            "ten_thuy_dien": "Sử Pán 1",
            "tinh_trang": null,
            "tren_song": "Ngòi Bo",
            "vi_do": 103.91512,
            "vi_tri_hanh_chinh": "xã Mường Hoa và Bản Hồ Tx. Sa Pa tỉnh Lào Cai",
            "von_dau_tu": null
        },
        {
            "chu_dau_tu": null,
            "cong_xuat": 34.5,
            "dung_tich": null,
            "kinh_do": 22.271888,
            "loai": null,
            "loai_hinh": null,
            "luu_vuc": null,
            "nam_hoat_dong": "7/4/1905",
            "nam_khoi_cong": "6/28/1905",
            "quy_mo": null,
            "san_luong": 165.0,
            "ten_thuy_dien": "Sử Pán 2",
            "tinh_trang": null,
            "tren_song": "Ngòi Bo",
            "vi_do": 103.942384,
            "vi_tri_hanh_chinh": "xã Mường Hoa và Bản Hồ Tx. Sa Pa tỉnh Lào Cai",
            "von_dau_tu": null
        }
    ]
};